### ISSUE TITLE
Patchi saunavisio -version luomiseksi

### ISSUE THREAD

**Issue by jkpj** [anylonen/XBMC-Elisa-Viihde-plugin#4]
Pienillä allaolevilla muokkauksilla toimii saunavision kanssa, tosin ohjelman kestoa ja katselukertoja ei näköjään saunavision jsonista löydy, joten näitä ei sitten xbmc:n puolella näy. Saunavision omassa web-käyttöliittymässä kesto ja koko ovat näkyvillä, joten nuokin saisi toimimaan parsimalla html:ää jsonin käyttämisen sijaan. Grafiikkaa en muuttanut joten kuvakkeena tämä näyttää nyt sitten edelleen elisa viihdettä.

Muokkaus: Jaa, enpä tiedä saako tätä kukaan muu kuin projektin omistaja ja minä tästä kelvollisena pätchinä auki - mutta jospa vaikka omistaja ottaisi tästä erilliseen patchifailiin ja laittaisi gittiin niin sitten halukkaat voisivat käyttää.

diff -cr plugin.video.elisa.viihde/addon.xml plugin.video.saunavisio/addon.xml
*** plugin.video.elisa.viihde/addon.xml	2012-06-13 17:15:16.000000000 +0300
--- plugin.video.saunavisio/addon.xml	2012-10-19 17:54:44.209428952 +0300
***************
*** 1,5 ****
  <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
! <addon id="plugin.video.elisa.viihde" name="Elisa Viihde" version="0.0.5" provider-name="zippoman, purtsi, teerytko">
      <requires>
          <import addon="xbmc.python" version="2.0"/>
          <import addon="script.module.simplejson" version="2.0.9"/>
--- 1,5 ----
  <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
! <addon id="plugin.video.saunavisio" name="Saunavisio" version="0.0.5" provider-name="zippoman, purtsi, teerytko">
      <requires>
          <import addon="xbmc.python" version="2.0"/>
          <import addon="script.module.simplejson" version="2.0.9"/>
***************
*** 9,17 ****
      </extension>
      <extension point="xbmc.addon.metadata">
          <platform>all</platform>
!         <summary lang="en">Elisa Viihde</summary>
!         <summary lang="fi">Elisa Viihde</summary>
!         <description lang="en">This XBMC plugin enables viewing Elisa Viihde recordings</description>
!         <description lang="fi">Tämän XBMC-pluginin avulla voit katsella Elisa Viihde-tallenteita</description>
      </extension>
  </addon>
--- 9,17 ----
      </extension>
      <extension point="xbmc.addon.metadata">
          <platform>all</platform>
!         <summary lang="en">Saunavisio</summary>
!         <summary lang="fi">Saunavisio</summary>
!         <description lang="en">This XBMC plugin enables viewing Saunavisio recordings</description>
!         <description lang="fi">Tämän XBMC-pluginin avulla voit katsella Saunavisio-tallenteita</description>
      </extension>
  </addon>
diff -cr plugin.video.elisa.viihde/changelog.txt plugin.video.saunavisio/changelog.txt
*** plugin.video.elisa.viihde/changelog.txt	2012-06-13 17:15:16.000000000 +0300
--- plugin.video.saunavisio/changelog.txt	2012-10-19 18:18:05.872379417 +0300
***************
*** 1,3 ****
--- 1,6 ----
+ [B]0.0.5.dev-saunavisio[/B]
+ - Changes for Saunavisio
+ 
  [B]0.0.5.dev[/B]
  - Ohjelma linkki on suora soita linkki ja info siirretty infon (i-näppäin) taakse
  - Koko title playeriin 
Vain hakemistossa plugin.video.saunavisio: changelog.txt~
diff -cr plugin.video.elisa.viihde/default.py plugin.video.saunavisio/default.py
*** plugin.video.elisa.viihde/default.py	2012-06-13 17:15:16.000000000 +0300
--- plugin.video.saunavisio/default.py	2012-10-20 13:48:05.169600864 +0300
***************
*** 31,37 ****
      import xbmcgui
      import xbmcaddon
      import simplejson
!     __settings__ = xbmcaddon.Addon(id='plugin.video.elisa.viihde')
      __language__ = __settings__.getLocalizedString
      BASE_RESOURCE_PATH = xbmc.translatePath( os.path.join( __settings__.getAddonInfo('path'), "resources" ) )
      sys.path.append( os.path.join( BASE_RESOURCE_PATH, "lib" ) )
--- 31,37 ----
      import xbmcgui
      import xbmcaddon
      import simplejson
!     __settings__ = xbmcaddon.Addon(id='plugin.video.saunavisio')
      __language__ = __settings__.getLocalizedString
      BASE_RESOURCE_PATH = xbmc.translatePath( os.path.join( __settings__.getAddonInfo('path'), "resources" ) )
      sys.path.append( os.path.join( BASE_RESOURCE_PATH, "lib" ) )
***************
*** 39,45 ****
  except ImportError:
      pass
  
! #Elisa Viihde
  
  import BeautifulSoup
  
--- 39,45 ----
  except ImportError:
      pass
  
! #Saunavisio
  
  import BeautifulSoup
  
***************
*** 61,72 ****
                                     ))
  
  def get_login_url(username, password):
!     return "http://elisaviihde.fi/etvrecorder/login.sl?username=" + username + "&password=" + password + "&savelogin=true&ajax=true"
  
  #logging in
  def login(username=None, password=None):
      if 'xbmc' in globals():
!         COOKIEFILE = xbmc.translatePath('special://profile/addon_data/plugin.video.elisa.viihde/cookies.lwp')
      else:
          COOKIEFILE = ''
      if username == None:
--- 61,72 ----
                                     ))
  
  def get_login_url(username, password):
!     return "http://www.saunavisio.fi/tvrecorder/index.sl?username=" + username + "&password=" + password + "&savelogin=true&ajax=true"
  
  #logging in
  def login(username=None, password=None):
      if 'xbmc' in globals():
!         COOKIEFILE = xbmc.translatePath('special://profile/addon_data/plugin.video.saunavisio/cookies.lwp')
      else:
          COOKIEFILE = ''
      if username == None:
***************
*** 146,152 ****
  
  def search_items(qstr):
      print "search_items: " + qstr
!     prog_url = "http://elisaviihde.fi/etvrecorder/search.sl?q=" + str(qstr)
      req = urllib2.Request(prog_url)
      response = urllib2.urlopen(req)
      search_html = response.read()
--- 146,152 ----
  
  def search_items(qstr):
      print "search_items: " + qstr
!     prog_url = "http://www.saunavisio.fi/tvrecorder/search.sl?q=" + str(qstr)
      req = urllib2.Request(prog_url)
      response = urllib2.urlopen(req)
      search_html = response.read()
***************
*** 203,209 ****
  
  
  def get_prog_data(prog_id):
!     prog_url = "http://elisaviihde.fi/etvrecorder/program.sl?programid=" + str(prog_id) + "&ajax"
      req = urllib2.Request(prog_url)
      response = urllib2.urlopen(req)
      link = response.read()
--- 203,209 ----
  
  
  def get_prog_data(prog_id):
!     prog_url = "http://www.saunavisio.fi/tvrecorder/program.sl?programid=" + str(prog_id) + "&ajax"
      req = urllib2.Request(prog_url)
      response = urllib2.urlopen(req)
      link = response.read()
***************
*** 236,242 ****
      listitem.setInfo('video', {'Title': name, 'plot': prog_data['short_text']})
      xbmc.Player().play(url, listitem)
      #mark program watched
!     view_url = "http://elisaviihde.fi/etvrecorder/program.sl?programid=" + str(prog_id) + "&view=true"
      urllib2.urlopen(view_url)
      return True
  
--- 236,242 ----
      listitem.setInfo('video', {'Title': name, 'plot': prog_data['short_text']})
      xbmc.Player().play(url, listitem)
      #mark program watched
!     view_url = "http://www.saunavisio.fi/tvrecorder/program.sl?programid=" + str(prog_id) + "&view=true"
      urllib2.urlopen(view_url)
      return True
  
***************
*** 266,272 ****
          #show directory by id
          folder_id = str(id)
  
!     folder_url = "http://elisaviihde.fi/etvrecorder/ready.sl?folderid=" + folder_id + "&ajax"
      response = urllib2.urlopen(folder_url)
      link = response.read()
      link = fix_chars(link)
--- 266,272 ----
          #show directory by id
          folder_id = str(id)
  
!     folder_url = "http://www.saunavisio.fi/tvrecorder/ready.sl?folderid=" + folder_id + "&ajax"
      response = urllib2.urlopen(folder_url)
      link = response.read()
      link = fix_chars(link)
***************
*** 285,296 ****
  
      #list recordings
      for row in data['recordings']:
!         if row['viewcount'] == "0":
              print_star = "* "
          else:
              print_star = ""
  
!         parsed_time = time.strptime(row['timestamp'][:-5], "%Y-%m-%dT%H:%M:%S")
          weekday_numb = int(time.strftime("%w", parsed_time))
  
          starttime = time.strftime("%d.%m %H:%M", parsed_time)
--- 285,300 ----
  
      #list recordings
      for row in data['recordings']:
!         if row.get('viewcount', "0") == "0":
              print_star = "* "
          else:
              print_star = ""
  
!         #parsed_time = time.strptime(row['timestamp'][:-5], "%Y-%m-%dT%H:%M:%S")
!         #timestamp = row.get('timestamp', "2012-01-01T0:00:00")
!         timestamp = row.get('start_time', "to 01.01.2012 00:00")
!         #parsed_time = time.strptime(timestamp, "%Y-%m-%dT%H:%M:%S")
!         parsed_time = time.strptime(timestamp[3:], "%d.%m.%Y %H:%M")
          weekday_numb = int(time.strftime("%w", parsed_time))
  
          starttime = time.strftime("%d.%m %H:%M", parsed_time)
***************
*** 306,317 ****
              date_name = str(vkopaivat[weekday_numb]) + " " + time.strftime("%d.%m.%Y %H:%M", parsed_time)
  
          name = print_star + row['name'] + " (" + row['channel'] + ", " + date_name + ")"
  
          link = add_watch_link(name,
                     row['program_id'],
!                    playcount=row['viewcount'],
                     totalItems=totalItems,
!                    duration=row['length'],
                     date=date_name
                     )
          t = UpdateProgramDataThread(row['program_id'],
--- 310,325 ----
              date_name = str(vkopaivat[weekday_numb]) + " " + time.strftime("%d.%m.%Y %H:%M", parsed_time)
  
          name = print_star + row['name'] + " (" + row['channel'] + ", " + date_name + ")"
+         #for key in row:
+         #    name = name + key
  
          link = add_watch_link(name,
                     row['program_id'],
!                    #playcount=row['viewcount'],
!                    playcount=0,
                     totalItems=totalItems,
!                    #duration=row['length'],
!                    duration=50,
                     date=date_name
                     )
          t = UpdateProgramDataThread(row['program_id'],

**Comment by anylonen** [comment]
Ei toteuteta.
