### ISSUE TITLE
Elisa viihde plugin crash addon.py "thread error"

### ISSUE THREAD

**Issue by attley86** [anylonen/XBMC-Elisa-Viihde-plugin#6]
Tervehdys,

Koitin tuossa asennella (uusimmalle?) raspbmc distrolle tuota elisaviihde pluginia ja saan joka kerta saman herjan kun koitan kirjautua palveluun:

"Skripti virhe: addon.py"

xbmc logi:

08:56:27 T:2871948352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following erro>
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'thread.error'>
Error Contents: can't start new thread
Traceback (most recent call last):
File "/home/pi/.xbmc/addons/XBMC-Elisa-Viihde-plugin-master/addon.py", line 401,>
mainloop()
File "/home/pi/.xbmc/addons/XBMC-Elisa-Viihde-plugin-master/addon.py", line 388,>
show_dir("0")
File "/home/pi/.xbmc/addons/XBMC-Elisa-Viihde-plugin-master/addon.py", line 333,>
t.start()
File "/usr/lib/python2.7/threading.py", line 495, in start
_start_new_thread(self.__bootstrap, ())
error: can't start new thread
-->End of Python script error report<--

Raspbmc koneen versiotiedot:

pi@raspbmc:~$ cat /scripts/upd_hist/build_info
raspbmc-rls-1.0-hardfp-b20131019-u20131019
pi@raspbmc:~$ grep XBMC .xbmc/temp/xbmc.log | head -1
08:52:46 T:3041100320  NOTICE: Starting XBMC (12.2 Git:20130502-32b1a5e), Platform: Linux (Debian GNU/Linux 7.2 (n/a), 3.10.15 armv6l). Built on Sep 28 2013
pi@raspbmc:~$

Elisa viihde plugin versiotiedot:
versio 0.0.6
(ladattu 20131020 tiedosto: XBMC-Elisa-Viihde-plugin-master.zip
Osoite: https://github.com/anylonen/XBMC-Elisa-Viihde-plugin/archive/master.zip)
Asennettu zip purkuna manuaalisesti, ei suoraan xbmc videopluggareista.

Osaako joku sanoa mistä kiikastaa?

**Comment by anylonen** [comment]
Cannot reproduce.
